//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIPatient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PATIENTDBEntities2 : DbContext
    {
        public PATIENTDBEntities2()
            : base("name=PATIENTDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbobservationpatient> tbobservationpatients { get; set; }
        public virtual DbSet<tbadresse> tbadresses { get; set; }
        public virtual DbSet<tbobservation> tbobservations { get; set; }
        public virtual DbSet<tbpatient> tbpatients { get; set; }
        public virtual DbSet<tbpersonne> tbpersonnes { get; set; }
        public virtual DbSet<tbrefobservation> tbrefobservations { get; set; }
    }
}
