//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbadresse
    {
        public long id { get; set; }
        public Nullable<long> personneid { get; set; }
        public string description { get; set; }
        public Nullable<bool> isactif { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    }
}
